#! /bin/bash

mv *.csv archive/
D=`date +"%Y-%m-%d %H:%M:%S"`
for i in {1..100}
do
	dotnet run -c release -- $i &
done


for i in {1..500}
do
	sleep 1
	echo $i/$TIMEOUT
done

echo "Timeout passed. Mering csv files"
cat *.csv | grep -v "QueryDate" | sort > "all $D.csv"
