#! /bin/bash

mv *.csv archive/
D=`date +"%Y-%m-%d %H:%M:%S"`
for i in {1..100}
do
	dotnet run -c release -- $i &
done

sleep 180
echo "Timeout passed. Mering csv files"
cat *.csv | grep -v "QueryDate" | sort > "all $D.csv"
